# Security Configuration for Arbitration Detection System
# OWASP Top 10 Compliant Configuration

# Authentication Configuration
authentication:
  jwt:
    algorithm: "HS256"
    access_token_expire_minutes: 30
    refresh_token_expire_days: 7
    secret_key: "${JWT_SECRET_KEY}"  # Use environment variable
  
  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_digits: true
    require_special_chars: true
    max_age_days: 90
    history_count: 5  # Remember last 5 passwords
    lockout_attempts: 5
    lockout_duration_minutes: 15
  
  mfa:
    enabled: true
    required_for_admin: true
    backup_codes_count: 10
    totp_window: 1
  
  session:
    timeout_minutes: 60
    absolute_timeout_hours: 24
    concurrent_sessions: 3
    secure_cookie: true
    same_site: "strict"
    http_only: true

# Authorization Configuration
authorization:
  rbac:
    enabled: true
    default_role: "read_only"
    admin_roles:
      - "super_admin"
      - "admin"
  
  api_keys:
    max_per_user: 5
    default_expiry_days: 365
    rotation_reminder_days: 30
    require_ip_whitelist: false

# Encryption Configuration
encryption:
  data_at_rest:
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
    enable_field_encryption: true
    encrypted_fields:
      - "ssn"
      - "credit_card"
      - "bank_account"
      - "personal_data"
  
  data_in_transit:
    tls_version: "1.3"
    cipher_suites:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
      - "TLS_AES_128_GCM_SHA256"
    hsts:
      enabled: true
      max_age: 31536000
      include_subdomains: true
      preload: true
  
  key_management:
    use_hsm: false  # Hardware Security Module
    use_kms: false  # Key Management Service
    master_key_source: "environment"  # environment, file, hsm, kms

# Audit Configuration
audit:
  enabled: true
  retention_days: 2555  # 7 years for compliance
  
  log_events:
    authentication: true
    authorization: true
    data_access: true
    data_modification: true
    configuration_changes: true
    security_events: true
  
  siem_integration:
    enabled: false
    endpoints: []
    format: "CEF"  # Common Event Format
    real_time: true
  
  compliance:
    standards:
      - "SOC2"
      - "GDPR"
      - "HIPAA"
      - "PCI_DSS"
    report_frequency: "monthly"
    auto_generate_reports: true

# Security Scanning Configuration
security_scanning:
  file_upload:
    enabled: true
    max_file_size_mb: 100
    scan_for_malware: true
    scan_for_injection: true
    quarantine_infected: true
    
    allowed_mime_types:
      - "text/plain"
      - "application/pdf"
      - "image/jpeg"
      - "image/png"
      - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    
    blocked_extensions:
      - ".exe"
      - ".dll"
      - ".bat"
      - ".cmd"
      - ".scr"
      - ".vbs"
      - ".js"
  
  content_security:
    sanitize_html: true
    sanitize_sql: true
    sanitize_json: true
    sanitize_xml: true
    prevent_xxe: true
    prevent_ssrf: true
  
  antivirus:
    engine: "clamav"
    update_definitions: true
    update_frequency: "daily"
    real_time_protection: true

# Rate Limiting Configuration
rate_limiting:
  enabled: true
  
  default:
    requests: 100
    window_seconds: 60
    strategy: "sliding_window"  # fixed_window, sliding_window, token_bucket, leaky_bucket
    burst: 10
  
  endpoints:
    "/api/auth/login":
      requests: 5
      window_seconds: 300
      strategy: "sliding_window"
      block_duration: 900
    
    "/api/auth/register":
      requests: 3
      window_seconds: 3600
      strategy: "fixed_window"
    
    "/api/analysis/detect":
      requests: 50
      window_seconds: 60
      strategy: "token_bucket"
      burst: 20
    
    "/api/documents/upload":
      requests: 10
      window_seconds: 60
      strategy: "leaky_bucket"
  
  ip_reputation:
    enabled: true
    initial_score: 100
    violation_penalty: 10
    block_threshold: 20
    recovery_rate: 1  # Points per hour
  
  ddos_protection:
    enabled: true
    detection_threshold: 10000  # Requests per minute
    mitigation_mode: "adaptive"  # block, throttle, adaptive
    alert_threshold: 5000

# Security Headers Configuration
security_headers:
  content_security_policy:
    default_src: "'self'"
    script_src: "'self' 'unsafe-inline'"
    style_src: "'self' 'unsafe-inline'"
    img_src: "'self' data: https:"
    font_src: "'self' data:"
    connect_src: "'self'"
    frame_ancestors: "'none'"
    base_uri: "'self'"
    form_action: "'self'"
  
  additional_headers:
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"
    Referrer-Policy: "strict-origin-when-cross-origin"
    Permissions-Policy: "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"

# CORS Configuration
cors:
  enabled: true
  allow_origins:
    - "https://app.example.com"
    - "https://admin.example.com"
  allow_credentials: true
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Authorization"
    - "Content-Type"
    - "X-API-Key"
    - "X-Request-ID"
  expose_headers:
    - "X-RateLimit-Limit"
    - "X-RateLimit-Remaining"
    - "X-RateLimit-Reset"
  max_age: 86400

# Input Validation Configuration
input_validation:
  max_string_length: 10000
  max_array_length: 1000
  max_json_depth: 10
  max_request_size_mb: 10
  
  sql_injection_prevention:
    enabled: true
    use_parameterized_queries: true
    escape_special_characters: true
    validate_input_types: true
  
  xss_prevention:
    enabled: true
    html_encoding: true
    attribute_encoding: true
    javascript_encoding: true
    css_encoding: true
    url_encoding: true

# Secrets Management
secrets_management:
  provider: "environment"  # environment, vault, aws_secrets_manager, azure_key_vault
  rotation:
    enabled: true
    frequency_days: 90
    automatic: false
  
  api_keys:
    min_length: 32
    charset: "alphanumeric"
    prefix: "ak_"
  
  database:
    encrypt_connection_string: true
    rotate_passwords: true
    password_complexity: "high"

# Monitoring and Alerting
monitoring:
  security_events:
    failed_login_threshold: 5
    permission_denied_threshold: 10
    malware_detection: "immediate"
    injection_attempt: "immediate"
    
  alerts:
    channels:
      - "email"
      - "slack"
      - "siem"
    
    email:
      recipients:
        - "security@example.com"
      smtp_server: "smtp.example.com"
      smtp_port: 587
      use_tls: true
    
    slack:
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channel: "#security-alerts"
    
  metrics:
    collect_performance: true
    collect_security: true
    retention_days: 90
    export_format: "prometheus"

# Backup and Recovery
backup:
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key_management: "separate"
  
  retention:
    daily: 7
    weekly: 4
    monthly: 12
    yearly: 7
  
  verification:
    enabled: true
    frequency: "weekly"
    restore_test: "monthly"

# Development vs Production Settings
environments:
  development:
    debug: true
    strict_mode: false
    mock_external_services: true
    
  staging:
    debug: false
    strict_mode: true
    mock_external_services: false
    
  production:
    debug: false
    strict_mode: true
    require_https: true
    require_mfa: true
    audit_all_events: true
    zero_trust: true

# Zero Trust Configuration
zero_trust:
  enabled: false  # Enable in production
  
  network:
    segment_by_sensitivity: true
    micro_segmentation: true
    encrypted_internal_traffic: true
  
  identity:
    continuous_verification: true
    risk_based_authentication: true
    device_trust_scoring: true
  
  data:
    classification_required: true
    encryption_by_classification: true
    dlp_enabled: true  # Data Loss Prevention

# Compliance Configuration
compliance:
  gdpr:
    enabled: true
    data_retention_days: 1095  # 3 years
    right_to_forget: true
    data_portability: true
    consent_management: true
  
  hipaa:
    enabled: false
    phi_encryption: true
    access_logging: true
    minimum_necessary: true
  
  pci_dss:
    enabled: false
    card_data_encryption: true
    network_segmentation: true
    quarterly_scans: true
  
  sox:
    enabled: false
    change_management: true
    separation_of_duties: true