# White-label Platform Configuration

# Server Configuration
server:
  address: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "10s"
  max_header_bytes: 1048576  # 1MB
  
  # TLS Configuration
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
  
  # CORS Configuration
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    exposed_headers: ["X-Total-Count"]
    max_age: 86400
  
  # Rate Limiting
  rate_limit:
    enabled: true
    requests_per_hour: 1000
    burst_limit: 100
    window_size: "1h"

# Database Configuration
database:
  host: "localhost"
  port: 5432
  name: "whitelabel"
  user: "postgres"
  password: "postgres"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "1h"
  conn_max_idle_time: "10m"
  migrations_path: "migrations"
  auto_migrate: true

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  max_retries: 3
  pool_size: 10
  min_idle_conns: 2
  pool_timeout: "4s"
  idle_timeout: "5m"
  tls: false

# Security Configuration
security:
  jwt_secret: "your-super-secret-jwt-key-that-should-be-at-least-32-characters-long"
  jwt_expiration: "24h"
  refresh_token_expiration: "168h"  # 7 days
  encryption_key: "your-32-character-encryption-key"
  password_min_length: 8
  session_timeout: "24h"
  max_login_attempts: 5
  lockout_duration: "15m"
  require_https: false
  csrf_protection: true
  content_type_nosniff: true
  frame_options: "DENY"
  hsts_max_age: 31536000  # 1 year

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_enabled: true
  tracing_enabled: false
  log_level: "info"
  metrics_path: "/metrics"
  health_path: "/health"
  prometheus_enabled: true
  jaeger_enabled: false
  jaeger_endpoint: ""
  log_format: "json"
  metrics_retention: "15d"

# Storage Configuration
storage:
  type: "local"  # local, s3, gcs, azure
  local_path: "./storage"
  max_file_size: 10485760  # 10MB
  allowed_extensions: [".jpg", ".jpeg", ".png", ".gif", ".pdf", ".doc", ".docx"]
  cdn_enabled: false
  cdn_domain: ""
  
  # S3 Configuration (used when type is "s3")
  s3:
    region: ""
    bucket: ""
    access_key_id: ""
    secret_access_key: ""
    endpoint: ""
    use_ssl: true
    path_style: false

# Email Configuration
email:
  enabled: false
  provider: "smtp"  # smtp, sendgrid, ses
  from: "noreply@whitelabel-platform.com"
  from_name: "White-label Platform"
  reply_to: ""
  
  # SMTP Configuration
  smtp:
    host: ""
    port: 587
    username: ""
    password: ""
    use_tls: true

# Feature Flags
features:
  multi_tenancy: true
  customization: true
  advanced_analytics: false
  backup_restore: false
  api_versioning: true
  webhook_support: true
  audit_logging: true
  compliance_mode: false
  data_encryption: true
  sso: false