name: arbitration_sdk
description: Flutter SDK for arbitration clause detection and analysis
version: 1.0.0
homepage: https://github.com/arbitration-platform/flutter-sdk
repository: https://github.com/arbitration-platform/flutter-sdk
issue_tracker: https://github.com/arbitration-platform/flutter-sdk/issues
documentation: https://docs.arbitration-platform.com/flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  encrypted_shared_preferences: ^3.0.1
  
  # File & Media Handling
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  
  # OCR & ML
  google_mlkit_text_recognition: ^0.10.0
  tflite_flutter: ^0.10.4
  tflite_flutter_helper: ^0.3.1
  
  # Biometrics & Security
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # UI & Theming
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  
  # Utilities
  path: ^1.8.3
  equatable: ^2.0.5
  uuid: ^4.2.1
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  
  # Charts & Visualization
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^24.1.41
  
  # Custom Painters
  custom_paint: ^0.0.2
  
  # AR (optional)
  arcore_flutter_plugin: ^0.0.9
  arkit_plugin: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  drift_dev: ^2.14.1
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/models/
    - assets/translations/
  
  # Fonts
  fonts:
    - family: ArbitrationIcons
      fonts:
        - asset: assets/fonts/ArbitrationIcons.ttf

# Platform-specific configurations
flutter:
  plugin:
    platforms:
      android:
        package: com.arbitrationsdk.flutter
        pluginClass: ArbitrationSdkPlugin
        dartPluginClass: ArbitrationSdk
      ios:
        pluginClass: ArbitrationSdkPlugin
        dartPluginClass: ArbitrationSdk