# Loki Configuration for Log Aggregation
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

# Common configuration shared between components
common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

# Query range configuration
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

# Schema configuration
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Ruler configuration for alerting rules
ruler:
  alertmanager_url: http://alertmanager:9093
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules/fake
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true

# Analytics configuration
analytics:
  reporting_enabled: false

# Limits configuration
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m
  max_query_parallelism: 32
  max_streams_per_user: 10000
  max_line_size: 0
  max_line_size_truncate: false
  max_entries_limit_per_query: 5000
  max_global_streams_per_user: 5000
  unordered_writes: true
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20

# Chunk store configuration
chunk_store_config:
  max_look_back_period: 0s

# Table manager configuration
table_manager:
  retention_deletes_enabled: true
  retention_period: 168h  # 7 days

# Compactor configuration
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

# Frontend configuration
frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  tail_proxy_url: http://querier:3100

# Query frontend configuration  
query_scheduler:
  max_outstanding_requests_per_tenant: 256

# Ingester configuration
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /loki/wal

# Memberlist configuration
memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
    - loki:7946