# Network Topology Configuration
# Multi-region architecture for global <50ms latency
apiVersion: networking.k8s.io/v1
kind: NetworkTopology
metadata:
  name: global-arbitration-network
  namespace: production
spec:
  # Global Regions Configuration
  regions:
    # North America
    us-east-1:
      location: "Virginia, USA"
      provider: "aws"
      zones:
        - us-east-1a
        - us-east-1b
        - us-east-1c
      capacity:
        cpu: "100 cores"
        memory: "400GB"
        storage: "10TB"
      latency_targets:
        intra_region: "5ms"
        cdn_edge: "10ms"
    
    us-west-2:
      location: "Oregon, USA"
      provider: "aws"
      zones:
        - us-west-2a
        - us-west-2b
        - us-west-2c
      capacity:
        cpu: "80 cores"
        memory: "320GB"
        storage: "8TB"
      latency_targets:
        intra_region: "5ms"
        cdn_edge: "10ms"
    
    # Europe
    eu-west-1:
      location: "Ireland"
      provider: "aws"
      zones:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      capacity:
        cpu: "100 cores"
        memory: "400GB"
        storage: "10TB"
      latency_targets:
        intra_region: "5ms"
        cdn_edge: "10ms"
    
    eu-central-1:
      location: "Frankfurt, Germany"
      provider: "aws"
      zones:
        - eu-central-1a
        - eu-central-1b
        - eu-central-1c
      capacity:
        cpu: "60 cores"
        memory: "240GB"
        storage: "6TB"
      latency_targets:
        intra_region: "5ms"
        cdn_edge: "10ms"
    
    # Asia Pacific
    ap-southeast-1:
      location: "Singapore"
      provider: "aws"
      zones:
        - ap-southeast-1a
        - ap-southeast-1b
        - ap-southeast-1c
      capacity:
        cpu: "80 cores"
        memory: "320GB"
        storage: "8TB"
      latency_targets:
        intra_region: "5ms"
        cdn_edge: "10ms"
    
    ap-northeast-1:
      location: "Tokyo, Japan"
      provider: "aws"
      zones:
        - ap-northeast-1a
        - ap-northeast-1b
        - ap-northeast-1c
      capacity:
        cpu: "60 cores"
        memory: "240GB"
        storage: "6TB"
      latency_targets:
        intra_region: "5ms"
        cdn_edge: "10ms"

  # Network Architecture
  architecture:
    pattern: "hub-and-spoke"
    primary_region: "us-east-1"
    secondary_regions:
      - "eu-west-1"
      - "ap-southeast-1"
    
    # Inter-region connectivity
    transit_gateway:
      enabled: true
      encryption: "ipsec"
      bandwidth: "10Gbps"
      routing: "dynamic"
    
    # VPC Configuration
    vpc:
      cidr_blocks:
        us-east-1: "10.0.0.0/16"
        us-west-2: "10.1.0.0/16"
        eu-west-1: "10.2.0.0/16"
        eu-central-1: "10.3.0.0/16"
        ap-southeast-1: "10.4.0.0/16"
        ap-northeast-1: "10.5.0.0/16"
      
      subnets:
        public:
          cidr_suffix: "/24"
          zones_per_region: 3
        private:
          cidr_suffix: "/20"
          zones_per_region: 3
        database:
          cidr_suffix: "/24"
          zones_per_region: 3

  # Edge Computing Configuration
  edge_locations:
    cloudflare:
      total_locations: 270+
      key_cities:
        - "New York"
        - "Los Angeles"
        - "London"
        - "Frankfurt"
        - "Singapore"
        - "Tokyo"
        - "Sydney"
        - "Mumbai"
        - "São Paulo"
        - "Toronto"
      
      services:
        - "static_content_cache"
        - "ml_inference_edge"
        - "api_gateway_edge"
        - "ddos_protection"
        - "bot_management"

  # Performance Targets
  performance_sla:
    global_latency:
      static_content: "< 50ms"
      api_responses: "< 200ms"
      ml_inference: "< 500ms"
    
    availability:
      target: "99.99%"
      rpo: "1 hour"
      rto: "15 minutes"
    
    throughput:
      requests_per_second: "100,000"
      bandwidth: "10Gbps"
      concurrent_users: "1,000,000"

  # Traffic Routing
  traffic_management:
    geographic_routing:
      enabled: true
      routing_policy: "latency_based"
      health_check_interval: "30s"
      failover_threshold: "3 failures"
    
    load_distribution:
      algorithm: "weighted_round_robin"
      weights:
        us-east-1: 30
        eu-west-1: 25
        ap-southeast-1: 20
        us-west-2: 15
        eu-central-1: 5
        ap-northeast-1: 5

  # Network Security
  security:
    ddos_protection:
      provider: "cloudflare"
      capacity: "100Gbps+"
      attack_detection: "automatic"
    
    firewall:
      type: "web_application_firewall"
      rules_engine: "custom + owasp"
      geo_blocking: "enabled"
    
    encryption:
      in_transit: "tls_1.3"
      at_rest: "aes_256"
      key_management: "aws_kms"

  # Monitoring and Observability
  monitoring:
    real_user_monitoring:
      enabled: true
      sampling_rate: "100%"
      metrics:
        - "page_load_time"
        - "api_response_time"
        - "error_rates"
        - "geographic_performance"
    
    synthetic_monitoring:
      locations: 50+
      frequency: "1 minute"
      protocols:
        - "http/https"
        - "tcp"
        - "dns"
    
    alerting:
      latency_threshold: "100ms"
      error_rate_threshold: "1%"
      availability_threshold: "99.9%"

  # Capacity Planning
  auto_scaling:
    horizontal:
      min_instances: 3
      max_instances: 100
      target_cpu: "70%"
      target_memory: "80%"
      scale_up_cooldown: "300s"
      scale_down_cooldown: "900s"
    
    vertical:
      enabled: true
      cpu_range: "1-16 cores"
      memory_range: "2GB-64GB"

  # Disaster Recovery
  disaster_recovery:
    strategy: "multi_region_active_active"
    backup_regions:
      primary: "us-east-1"
      secondary: "eu-west-1"
      tertiary: "ap-southeast-1"
    
    data_replication:
      type: "synchronous"
      lag_tolerance: "< 1s"
      consistency: "eventual"
    
    failover:
      automatic: true
      detection_time: "30s"
      switch_time: "60s"
      rollback_time: "120s"